name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los días a la medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: RicardoMiguelR
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Subir Snake al repositorio
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
